services:
  app:
    image: notifications-image
    build: .
    container_name: notifications_container
    restart: always
    env_file: .env
    ports:
      - "8082:8888"
    networks:
      - library_network

volumes:
  notification-db:

networks:
  library_network:
    external: true