server:
  port: 8889
  error:
    include-message: always

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:29092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    web-application-type: servlet