spring:
  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: zchiernov1@gmail.com
    password: ogvjhbgnsjiktsqc
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true